version: '3.8'

services:
  molmo-demo:
    build: .
    ports:
      - "7860:7860"
    environment:
      - DEVICE=cpu  # Change to 'cuda' or 'cuda:0' for GPU
      - HF_HOME=/cache/huggingface
      - GRADIO_DEFAULT_CONCURRENCY_LIMIT=${GRADIO_DEFAULT_CONCURRENCY_LIMIT:-1}
    volumes:
      - ${DOCKER_HF_CACHE_PATH:-$HOME/.cache/huggingface}:/cache/huggingface/
    # Uncomment for running on GPU:
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]